# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Set timeout in milliseconds (1 hour = 3600000 milliseconds)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Debounce settings for Boba U4T switches
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5